name: Auto Commit and Push

on:
  push:
    paths:
      - 'soft.py'
      - 'requirements.txt'
      - 'README.md'
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  auto-commit-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - name: Commit and push changes
        run: |
          git add soft.py requirements.txt README.md || true
          git diff --cached --quiet || git commit -m "Auto-commit: update tracked files"
          git push || true
